'use client';
import { useMemo, useRef, useState } from 'react';
import Image from 'next/image';
import { ArrowDown, ArrowUpRight, ChevronDown, Disc3, Mail, Pause, Play } from 'lucide-react';

export type Service = { id:string; date:string; workshop:string; category:string; mileage?:number; mileageAnomaly?:boolean; summary:string; notes:string };
export type Asset = {name:string; src:string; date?:string; isPdf:boolean; label:string};
const fmtDate = (d:string) => new Intl.DateTimeFormat('es-AR',{dateStyle:'medium'}).format(new Date(`${d}T12:00:00`));
const fmtKm = (n:number) => new Intl.NumberFormat('es-AR').format(n);
const preview = 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/ef/54/3d/ef543d55-58cb-320e-8dc7-084336d961d0/mzaf_15679467696516524072.plus.aac.p.m4a';
const art = 'https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/e6/8a/68/e68a688e-129e-cb9d-938f-bc3ee37059ae/075679930910.jpg/300x300bb.jpg';

function MusicControl() {
  const [playing,setPlaying]=useState(false); const [failed,setFailed]=useState(false); const audio=useRef<HTMLAudioElement>(null);
  const toggle=()=>{ if(!audio.current || failed) return; if(playing) { audio.current.pause(); setPlaying(false); } else { audio.current.play().then(()=>setPlaying(true)).catch(()=>{setPlaying(false);setFailed(true)}); } };
  return <div className={`music ${playing?'is-playing':'is-paused'} ${failed?'is-failed':''}`}><audio ref={audio} src={preview} preload="none" onEnded={()=>setPlaying(false)} onError={()=>{setPlaying(false);setFailed(true)}}/><button className="music-button" aria-pressed={playing} aria-label={failed?'No se pudo cargar la canción':playing?'Pausar See You Again':'Reproducir See You Again'} onClick={toggle} disabled={failed}><span className="record"><Image src={art} alt="Portada de See You Again" width={48} height={48}/><span className="record-hole"/></span>{playing?<Pause size={14}/>:<Play size={14}/>}</button><span className="music-copy"><small>{failed?'Audio no disponible':playing?'Reproduciendo':'En pausa'}</small><a href="https://music.apple.com/us/album/see-you-again-feat-charlie-puth/966411595?i=966411602" target="_blank" rel="noreferrer">See You Again</a></span></div>;
}

function Empty({children}:{children:React.ReactNode}) { return <div className="empty"><div className="empty-icon"><Disc3 size={25}/></div><p>{children}</p></div>; }

export default function HarrisonExperience({services,current,details,records}:{services:Service[];current:Asset[];details:Asset[];records:Asset[]}) {
  const [open,setOpen]=useState<string|null>(null); const [selectedPhoto,setSelectedPhoto]=useState<Asset|null>(null);
  const [hoveredPoint,setHoveredPoint]=useState<{date:string;y:number;left:number;top:number}|null>(null);
  const ordered=[...services].reverse(); const linked=(date:string)=>records.filter(a=>a.date===date);
  const points=useMemo(()=>services.filter(s=>s.mileage).map(s=>({x:new Date(s.date).getTime(),y:s.mileage!,date:s.date})),[services]);
  const min=Math.min(...points.map(p=>p.y)), max=Math.max(...points.map(p=>p.y)); const chartW=900, chartH=300, pad=42;
  const pathD=points.map((p,i)=>`${i?'L':'M'} ${pad+(p.x-points[0].x)/(points.at(-1)!.x-points[0].x)*(chartW-pad*2)} ${chartH-pad-(p.y-min)/(max-min)*(chartH-pad*2)}`).join(' ');
  return <main>
    <header className="header"><a className="wordmark" href="#fotos">HARRISON<span>FIESTA 2012</span></a><nav>{[['fotos','Fotos'],['historial','Historial'],['kilometros','Kilómetros'],['detalles','Detalles'],['contacto','Contacto']].map(([id,l])=><a key={id} href={`#${id}`}>{l}</a>)}</nav><MusicControl/></header>
    <section id="fotos" className="hero"><div className="hero-bg">{current[0]&&<Image src={current[0].src} alt="Ford Fiesta 2012" fill priority sizes="100vw"/>}<div className="hero-shade"/></div><div className="hero-content"><p className="eyebrow">UNA HISTORIA SOBRE RUEDAS · 2012</p><h1>Ford Fiesta<br/><em>Harrison.</em></h1><p className="hero-lede">Una unidad con historia documentada, mantenida con cuidado y lista para su próxima etapa.</p>{current.length===0&&<p className="hero-photo-note">Las fotos reales aparecerán acá al agregarlas en <code>public/car/current/</code>.</p>}<div className="hero-actions"><a className="button button-primary" href="#contacto">Ver precio <ArrowDown size={16}/></a><a className="button button-ghost" href="#historial">Conocer la historia <ArrowDown size={16}/></a></div>{current.length>1&&<div className="hero-gallery" aria-label="Fotos actuales">{current.slice(0,5).map(a=><button key={a.name} onClick={()=>setSelectedPhoto(a)} aria-label={`Ampliar ${a.label}`}><Image src={a.src} alt="" width={84} height={58}/></button>)}</div>}</div><div className="hero-meta"><span>ÚLTIMO REGISTRO</span><strong>91.000 <small>KM</small></strong></div></section>
    <section className="intro-band"><p>La confianza se construye con evidencia.</p><span>01 / 04</span></section>
    <section id="historial" className="history section"><div className="section-heading"><p className="eyebrow">02 — HISTORIAL</p><h2>Lo que pasó,<br/><em>queda registrado.</em></h2><p>Un recorrido cronológico por servicios, reparaciones y mejoras. Abrí cada fecha para ver la información completa y sus comprobantes.</p></div><div className="history-grid"><div className="timeline">{ordered.map(s=><article className={`timeline-item ${open===s.id?'is-open':''}`} key={s.id}><div className="timeline-dot"/><button className="timeline-card" onClick={()=>setOpen(open===s.id?null:s.id)} aria-expanded={open===s.id} aria-controls={`detail-${s.id}`}><span className="timeline-date">{fmtDate(s.date)} · {s.workshop}</span><span className="timeline-title">{s.category}</span><span className="timeline-summary">{s.summary}</span><span className="timeline-meta">{s.mileage?`${fmtKm(s.mileage)} km${s.mileageAnomaly?' · lectura original':''}`:'Kilometraje no consignado'} <ChevronDown size={16}/></span></button>{open===s.id&&<div className="timeline-detail" id={`detail-${s.id}`}><p>{s.notes}</p>{linked(s.date).length>0?<div className="receipts">{linked(s.date).map(a=>a.isPdf?<a key={a.name} href={a.src} target="_blank" rel="noreferrer" className="receipt">{a.label} <ArrowUpRight size={14}/></a>:<button key={a.name} className="receipt receipt-image" onClick={()=>setSelectedPhoto(a)}><Image src={a.src} alt={a.label} width={160} height={110}/><span>{a.label}</span></button>)}</div>:<small className="muted">No hay comprobantes adjuntos para esta fecha todavía.</small>}</div>}</article>)}</div><aside className="polaroids"><p className="eyebrow">FRAGMENTOS</p>{current.slice(0,4).map((a,i)=><figure className={`polaroid p${i}`} key={a.name}><div>{<Image src={a.src} alt={a.label||'Foto del auto'} width={240} height={180}/>}</div><figcaption>{a.label||'Harrison · archivo personal'}</figcaption></figure>)}{current.length===0&&<Empty>Las fotos del auto aparecerán aquí cuando agregues archivos a <code>public/car/current/</code>.</Empty>}</aside></div></section>
    <section id="kilometros" className="mileage section"><div className="section-heading split"><div><p className="eyebrow">03 — KILÓMETROS</p><h2>La distancia<br/><em>también cuenta.</em></h2></div><div className="latest"><small>ÚLTIMO REGISTRO</small><strong>91.000 <i>km</i></strong></div></div><div className="chart-wrap">{points.length?<svg viewBox={`0 0 ${chartW} ${chartH}`} role="img" aria-label="Kilómetros registrados a través del tiempo" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2276d2" stopOpacity=".25"/><stop offset="1" stopColor="#2276d2" stopOpacity="0"/></linearGradient></defs><path d={`${pathD} L ${chartW-pad} ${chartH-pad} L ${pad} ${chartH-pad} Z`} fill="url(#fill)"/><path d={pathD} fill="none" stroke="#2276d2" strokeWidth="3" strokeLinecap="round"/>{points.map((p,i)=>{const cx=pad+(p.x-points[0].x)/(points.at(-1)!.x-points[0].x)*(chartW-pad*2);const cy=chartH-pad-(p.y-min)/(max-min)*(chartH-pad*2);return <circle key={`${p.date}-${i}`} cx={cx} cy={cy} r="6" fill="#fff" stroke="#2276d2" strokeWidth="3" tabIndex={0} role="button" aria-label={`${fmtDate(p.date)}: ${fmtKm(p.y)} kilómetros`} onMouseEnter={()=>setHoveredPoint({date:p.date,y:p.y,left:cx/chartW*100,top:cy/chartH*100})} onMouseLeave={()=>setHoveredPoint(null)} onFocus={()=>setHoveredPoint({date:p.date,y:p.y,left:cx/chartW*100,top:cy/chartH*100})} onBlur={()=>setHoveredPoint(null)}/>})}</svg>:<Empty>Aún no hay lecturas de kilometraje.</Empty>}{hoveredPoint&&<div className="chart-tooltip" style={{left:`${hoveredPoint.left}%`,top:`${hoveredPoint.top}%`}}><strong>{fmtKm(hoveredPoint.y)} km</strong><span>{fmtDate(hoveredPoint.date)}</span></div>}<div className="chart-axis"><span>{fmtDate(points[0]?.date||'2013-01-01')}</span><span>{fmtDate(points.at(-1)?.date||'2026-01-01')}</span></div></div></section>
    <section id="detalles" className="details section"><div className="section-heading"><p className="eyebrow">04 — DETALLES</p><h2>Las marcas<br/><em>también cuentan.</em></h2><p>Un archivo visual de los detalles estéticos de la unidad. Transparencia para mirar de cerca.</p></div>{details.length?<div className="details-grid">{details.map(a=><button key={a.name} onClick={()=>setSelectedPhoto(a)}><Image src={a.src} alt={a.label} width={500} height={380}/><span>{a.label}</span></button>)}</div>:<Empty>Agregá imágenes a <code>public/car/details/</code> para mostrar aquí los detalles estéticos.</Empty>}</section>
    <section id="contacto" className="contact section"><div><p className="eyebrow">HARRISON · FIESTA 2012</p><h2>Tu próxima<br/><em>historia empieza acá.</em></h2></div><div className="price"><small>PRECIO</small><strong>USD 10.000</strong><span>91.000 km · Año 2012</span><a className="button button-primary" href="mailto:nicozuzek@gmail.com?subject=Consulta%20Ford%20Fiesta%202012"><Mail size={17}/> Escribirme</a></div><p className="contact-note">¿Querés conocerlo? Escribime y coordinamos.</p></section>
    <footer><span>HARRISON / FIESTA 2012</span><span>Una presentación personal · No afiliado a Ford Motor Company</span></footer>
    {selectedPhoto&&<div className="lightbox" role="dialog" aria-modal="true" aria-label={selectedPhoto.label} onClick={()=>setSelectedPhoto(null)}><div onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelectedPhoto(null)} aria-label="Cerrar">×</button>{selectedPhoto.isPdf?<iframe src={selectedPhoto.src} title={selectedPhoto.label}/>:<Image src={selectedPhoto.src} alt={selectedPhoto.label} width={1000} height={800}/>}<p>{selectedPhoto.label}</p></div></div>}
  </main>;
}
